backend:
  name: git-gateway

locale: "it"

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Articolo" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data di pubblicazione", name: "date", widget: "datetime"}
      - {label: "Introduzione", name: "description", widget: "text"}
      - {label: "Immagine", name: "image", widget: "image", required: false}
      - {label: "Contenuto", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pagine"
    files:
      - file: "site/content/_index.md"
        label: "Pagina principale"
        name: "home"
        fields:
          - {label: "Titolo", name: title, widget: string}
          - {label: "Sottotitolo", name: subtitle, widget: string}
          - {label: "Immagine", name: image, widget: image}
          - {label: "Riassunto", name: blurb, widget: object, fields: [
              {label: "Titolo", name: "heading", widget: string},
              {label: "Testo", name: "text", widget: "text"}]}
          - {label: "Introduzione", name: intro, widget: object, fields: [
              {label: "Titolo", name: "heading", widget: string},
              {label: "Testo", name: "text", widget: "text"}]}
          - {label: "Camere", name: rooms, widget: list, fields: [
              {label: "Immagine", name: "image", widget: "image"},
              {label: "Testo", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contatti"
        name: "contact"
        fields:
          - {label: "Titolo", name: title, widget: string}
          - {label: "Logo", name: logo, widget: image}
          - {label: "Testo", name: body, widget: markdown}
          - label: "Contatto"
            name: contact_entries
            widget: list
            fields:
              - label: "Titolo"
                name: heading
                widget: string
              - label: "Testo"
                name: text
                widget: text
